services:
  waterkit:
    build:
      context: ./jupyterlab
      dockerfile: Dockerfile
    image: ${JP_IMAGE}
    container_name: ${JP_CONTAINER}
    ports:
      - "${JP_PORT}:7777"
    environment:  
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - "../:/home/waterkit/WATERKIT"
    labels:
      - "description=WaterKit Container"
      - "port=7777"
    networks:
      - waterkit

  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    container_name: waterkit-api
    restart: unless-stopped
    entrypoint: ""
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - "../:/home/waterkit/WATERKIT"
    networks:
      - waterkit

networks:
  waterkit:
    driver: bridge
   